version: "3.9"

services:
  user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: userDb
      MYSQL_USER: urzrus
      MYSQL_PASSWORD: rusurz
    volumes:
      - user_db_data:/var/lib/mysql
      - ./init_user_db.sql:/docker-entrypoint-initdb.d/init_user_db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 5

  data-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: dataDb
      MYSQL_USER: urzrus
      MYSQL_PASSWORD: rusurz
    volumes:
      - data_db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 5

  user-manager:
    build: ./user-manager
    container_name: user-manager
    ports:
      - "5003:5003"
    environment:
      - MYSQL_HOST=user-db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=urzrus
      - MYSQL_PASSWORD=rusurz
      - MYSQL_DATABASE=userDb
      - LISTEN_PORT=5003 # REST API
      - LISTEN_PORT_GRPC=50051
    depends_on:
      user-db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/50051" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - net

  data-collector:
    build: ./data-collector
    container_name: data-collector
    ports:
      - "5002:5002"
    environment:
      - MYSQL_HOST=data-db
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=urzrus
      - MYSQL_PASSWORD=rusurz
      - MYSQL_DATABASE=dataDb
      - LISTEN_PORT=5002 # REST API
      - GRPC_PORT=50051
    depends_on:
      user-manager:
          condition: service_healthy
      data-db:
          condition: service_healthy
    restart: always
    networks:
      - net

volumes:
  user_db_data:
  data_db_data:

networks:
  net:
    driver: bridge

